### PR TITLE
Fixed compatibility issue with Elementor v3.26

### LINKED ISSUE #882: Page builder widgets module incompatibility with Elementor 3.26 version
### Description

With Elementor version 3.26 released today our OrbitFox module Page builder widgets is not working.
If you have module enabled:
Image

Elementor sidebar loads forever:
Image

Such error was reported:
`Uncaught Error: Class “Elementor\Core\Schemes\Typography” not found in /wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php
`

Reported: https://wordpress.org/support/topic/plug-in-broke-after-elementor-update/

### Step-by-step reproduction instructions

1. Install latest Elementor version 3.26 and Orbitfox
2. Enable Page builder widgets module
3. Load any page built with Elementor - sidebar won't finish loading

### Screenshots, screen recording, code snippet or Help Scout ticket

_No response_

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary

I have updated the Elementor Typography implementation to reflect the latest changes.  
For more details on the updates in version 3.26, check the discussion here: [Elementor v3.26 Beta Release](https://github.com/orgs/elementor/discussions/29403).

### Typography Changes
https://developers.elementor.com/docs/deprecations/complex-example/

Close https://github.com/Codeinwp/themeisle-companion/issues/882

### Will affect visual aspect of the product
Yes

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes #882

### CODE REVIEW

File: obfx_modules/content-forms/includes/rest/server.php [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+			TI_CONTENT_FORMS_NAMESPACE,
+			'/submit',
+			array(
+				'methods'             => \WP_REST_Server::CREATABLE,
+				'callback'            => array( $this, 'submit_form' ),
+				'args'                => array(
+					'form_type'    => array(
+						'type'        => 'string',
+						'required'    => true,
+						'description' => __( 'What type of form is submitted.', 'textdomain' ),
```
Comment (Soare-Robert-Daniel) [inline obfx_modules/content-forms/includes/rest/server.php:36]: We need to make the domain consistent. Instead of `textdomain` you can use the plugin slug for it `'themeisle-companion'`

**Review by Soare-Robert-Daniel — APPROVED** [review]
It looks good. I left a comment about keeping the text domain the same so that users can have a better experience when they try to translate (manually or automatically).

File: obfx_modules/content-forms/includes/rest/server.php (hunk 1 above)
Comment (girishpanchal30) [reply obfx_modules/content-forms/includes/rest/server.php]: @Soare-Robert-Daniel Thank you for the review, I've changed the textdomain and pushed changes.
